# Generated by Django 4.1.3 on 2023-11-18 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('flights', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='flights.flight')),
            ],
        ),
    ]
